### ISSUE TITLE
Collections : data tab

### ISSUE THREAD

**Issue by kartsims** [apiko-rest-api/ui#10]
When clicking on a collection, there is a "Data" tab on the right side of the screen. This should show a default view of the data returned by the API.

**Comment by kasp1** [comment]
This Data tab should allow editing of the data in the selected collection, simple CRUD interface.

In order for this feature to allow management of all data in the database, the UI will have to bypass default endpoint access restrictions, which can be done by specifying the `secret` parameter (either as a GET parameter or in the request body) and supplying the server`s secret as its value. Whenever the UI connects to a server using a secret, the secret is held in the window.localStorage.

**Comment by ltbringer** [comment]
Is this something like phpmyadmin, where you click on a table name and you can view/edit/delete data and remove table?

**Comment by kasp1** [comment]
I would image it much simpler, simple data editing. When you are on this tab, you already have a table/collection selected. One should be able to list rows, edit values of cells, add/remove rows.

Like data editing in Deployd.
