### ISSUE TITLE
The endpoints menu should be more readable

### ISSUE THREAD

**Issue by kasp1** [apiko-rest-api/ui#19]
As of now the list of endpoints menu is a simple list, which with a lot of items decreases readability. Can we figure out a way how to make it more readable? E.g. by grouping of any kind?

**Comment by ltbringer** [comment]
Endpoints can be grouped by method type (this doesn't seem quite useful) or by having parent routes, for example:
- /users [GET]
- /users [POST]
- /users/:id [GET]
- /users/:id [PUT] 
- /users/:id [DELETE] 

Can be all grouped by /users, but in the case of:

- POST /users/password/change/:id core
- POST /users/password/reset/:id core

could be grouped by /users/password

**Comment by kasp1** [comment]
Good idea. If I further think about it, what about having expanding menus by the first chunk of the route?

E.g. we would have just `/users` in the menu with an expand button and if you would click it, the corresponding endpoints would appear:

```
/users ▼
- GET /users
- POST /users
- GET /users/:id
- PUT /users/:id
```

Would that even be possible?

**Comment by ltbringer** [comment]
Yeah, it should be do-able.

https://jsfiddle.net/codewingx/b7o0ucL5/3/ This design can help reducing the list further as all the method types will stack together under the same route and can be switched by clicking on them

**Comment by kasp1** [comment]
Looks great to me. Feel free to create a pull request. Please keep in mind that even beginners may want to use Apiko and the menu should be understandable for them.

Thank you :)

**Comment by ltbringer** [comment]
Sure, I'll give this a shot and create one.

**Comment by ilabacheuski** [comment]
Can we add filters? to group by finite route-endpoint, by method, by hierarchy of route?
Just a suggestion to keep in mind some day we will want such functionallity?

And also - should it be `<button>` or `<ul><li>`? Or even `ul>li>button`? How do you think, guys?
For buttons we also can use bulma css. Will be more uniformly

**Comment by ltbringer** [comment]
Please refer to this [bin,](https://jsbin.com/pekasob/edit?js,console) I am not sure why the console shows a stringified object, but on using a browser console, you can see the object that I would use to create the list. It can support the dropdown for child routes, methods, and I believe having filters too will not be an issue. I am open to suggestions for the structuring of the object.

It could be `<ul><li><button>...` as it is a list of methods that are applicable to the particular route.

**Comment by ilabacheuski** [comment]
browsers console specially convert every object before output. [object Object] - is just normal behaviour.
It's possible to have different vue templates and some different objects to fill in those templates. So we can have different styles of view for user(by route, by method, by hierarchy). filters can by applied to those objects. Vue can switch templates and form objects as you did in bin

**Comment by kasp1** [comment]
Alright @CodeWingX please give it a go and let's what will it look like. :) feel free to ask any questions meanwhile

**Comment by kasp1** [comment]
Thank you very much @CodeWingX for taking care of this. Brilliant.
