### ISSUE TITLE
FAQ / SO overlay

### ISSUE THREAD

**Issue by kasp1** [apiko-rest-api/ui#3]
Suggested UX:

![apiko-faqoverlay](https://cloud.githubusercontent.com/assets/11492515/23331912/2ced5770-fb67-11e6-8c49-edc0e2c25c18.png)

**Comment by SystemZ** [comment]
This page should be activated by this current button or some brand new?
![screenshot from 2017-02-26 15-57-00](https://cloud.githubusercontent.com/assets/1836094/23340766/4159b354-fc3c-11e6-86d6-92c249886d4d.png)

**Comment by kasp1** [comment]
Hm actually, it could be this button I think. At least for now.

**Comment by kasp1** [comment]
Any further progress here? Are we stuck with anything?

**Comment by kasp1** [comment]
It seems like the StackOverflow part is more or less done. The Guide part is yet to be done. The guide contents can be read from https://github.com/apiko-rest-api/apiko-userguide/blob/master/Index.md

Perhaps the guide should be fetched real time directly from GitHub. There should also be a link to edit the currently displayed guide page.

Anyone to finish this?

**Comment by kasp1** [comment]
Thanks @EMCM for finishing this.
