### ISSUE TITLE
Guide: Guide Topics remains in left column

### ISSUE THREAD

**Issue by erikcr** [apiko-rest-api/ui#30]
It was hard to explain this in a single statement, but essentially the Guide Topics would remain in the left column after the heading is selected to view the content, instead of expanding to take of the SO column.

Currently clicking a header will display:
![image](https://cloud.githubusercontent.com/assets/4974496/25776403/45ff7bfc-328b-11e7-8632-7d69c069ffa6.png)

I think it should be changed to display:
![image](https://cloud.githubusercontent.com/assets/4974496/25776407/5475ab3e-328b-11e7-8c81-40db9f81ac1e.png)
where the user could look at the instructions and the SO list at the same time.

**Comment by kasp1** [comment]
This was actually my original idea, but then other suggested to stretch open articles to the whole width. So I changed the UX to full width for articles. Will it work well?

**Comment by erikcr** [comment]
I originally thought it looked cleaner when they remain as two separate columns instead of full width, because some of the articles have a lot of white space. However the longer articles look better with full width. So I guess that means I just need to help add more content to the documentation :D
